### ISSUE TITLE
上传图片时候报错了

### ISSUE THREAD

**Issue by halfrost** [JaxsonWang/Ghost-QiNiu-Store#1]
```
ERROR "POST /ghost/api/v3/admin/images/upload/" 500 5642ms

NAME: InternalServerError
CODE: ERR_INVALID_ARG_TYPE
MESSAGE: The "url" argument must be of type string. Received type undefined

level: normal

InternalServerError: The "url" argument must be of type string. Received type undefined
    at new GhostError (/var/www/ghost/versions/3.26.1/node_modules/@tryghost/errors/lib/errors.js:10:26)
    at _private.prepareError (/var/www/ghost/versions/3.26.1/core/server/web/shared/middlewares/error-handler.js:53:19)
    at Layer.handle_error (/var/www/ghost/versions/3.26.1/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/var/www/ghost/versions/3.26.1/node_modules/express/lib/router/index.js:315:13)
    at /var/www/ghost/versions/3.26.1/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost/versions/3.26.1/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost/versions/3.26.1/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/var/www/ghost/versions/3.26.1/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/var/www/ghost/versions/3.26.1/node_modules/express/lib/router/index.js:315:13)
    at /var/www/ghost/versions/3.26.1/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost/versions/3.26.1/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost/versions/3.26.1/node_modules/express/lib/router/index.js:275:10)
    at /var/www/ghost/versions/3.26.1/node_modules/express/lib/router/index.js:635:15
    at next (/var/www/ghost/versions/3.26.1/node_modules/express/lib/router/index.js:260:14)
    at next (/var/www/ghost/versions/3.26.1/node_modules/express/lib/router/route.js:127:14)
    at /var/www/ghost/versions/3.26.1/core/server/api/shared/http.js:96:17
    at tryCatcher (/var/www/ghost/versions/3.26.1/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/www/ghost/versions/3.26.1/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/var/www/ghost/versions/3.26.1/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/var/www/ghost/versions/3.26.1/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/var/www/ghost/versions/3.26.1/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/var/www/ghost/versions/3.26.1/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/var/www/ghost/versions/3.26.1/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/var/www/ghost/versions/3.26.1/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/var/www/ghost/versions/3.26.1/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:439:21)
    at process.topLevelDomainCallback (domain.js:130:23)

TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Url.parse (url.js:155:3)
    at urlParse (url.js:150:13)
    at Object.urlResolve [as resolve] (url.js:660:10)
    at /var/www/ghost/content/adapters/storage/qn-store/src/index.js:97:24
    at tryCatcher (/var/www/ghost/versions/3.26.1/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/www/ghost/versions/3.26.1/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/var/www/ghost/versions/3.26.1/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/var/www/ghost/versions/3.26.1/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/var/www/ghost/versions/3.26.1/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/var/www/ghost/versions/3.26.1/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/var/www/ghost/versions/3.26.1/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/var/www/ghost/versions/3.26.1/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/var/www/ghost/versions/3.26.1/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:439:21)
    at process.topLevelDomainCallback (domain.js:130:23)
```
错误出现在 `qn-store/src/index.js:97:24`, 校验 url 的时候拿到了一个 undefined。

我的配置文件是：
```
  "storage": {
    "active": "qn-store",
    "qn-store": {
      "accessKey": "XXXX",
      "secretKey": "XXXX",
      "bucket": "XXX",
      "origin": "https://XXXX.com",
      "format": "${year}/${month}/${name}${ext}"
    }
  },
```

**Comment by halfrost** [comment]
哎呀。。我的锅。。之前配置的图床地址是 origin，现在你的改成了 domain。。sorry~ 没问题的哈~
