### ISSUE TITLE
上传图片报错

### ISSUE THREAD

**Issue by halfrost** [JaxsonWang/Ghost-QiNiu-Store#2]
```
ERROR "POST /ghost/api/v3/admin/images/upload/" 500 514ms

NAME: InternalServerError
MESSAGE: expired token

level: normal

InternalServerError: expired token
    at new GhostError (/var/www/ghost/versions/3.26.1/node_modules/@tryghost/errors/lib/errors.js:10:26)
    at _private.prepareError (/var/www/ghost/versions/3.26.1/core/server/web/shared/middlewares/error-handler.js:53:19)
    at Layer.handle_error (/var/www/ghost/versions/3.26.1/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/var/www/ghost/versions/3.26.1/node_modules/express/lib/router/index.js:315:13)
    at /var/www/ghost/versions/3.26.1/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost/versions/3.26.1/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost/versions/3.26.1/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/var/www/ghost/versions/3.26.1/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/var/www/ghost/versions/3.26.1/node_modules/express/lib/router/index.js:315:13)
    at /var/www/ghost/versions/3.26.1/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost/versions/3.26.1/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost/versions/3.26.1/node_modules/express/lib/router/index.js:275:10)
    at /var/www/ghost/versions/3.26.1/node_modules/express/lib/router/index.js:635:15
    at next (/var/www/ghost/versions/3.26.1/node_modules/express/lib/router/index.js:260:14)
    at next (/var/www/ghost/versions/3.26.1/node_modules/express/lib/router/route.js:127:14)
    at /var/www/ghost/versions/3.26.1/core/server/api/shared/http.js:96:17
    at tryCatcher (/var/www/ghost/versions/3.26.1/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/www/ghost/versions/3.26.1/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/var/www/ghost/versions/3.26.1/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/var/www/ghost/versions/3.26.1/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/var/www/ghost/versions/3.26.1/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/var/www/ghost/versions/3.26.1/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/var/www/ghost/versions/3.26.1/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/var/www/ghost/versions/3.26.1/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/var/www/ghost/versions/3.26.1/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:439:21)
    at process.topLevelDomainCallback (domain.js:130:23)

Error: expired token
    at /var/www/ghost/content/adapters/storage/qn-store/src/index.js:86:60
    at /var/www/ghost/content/adapters/storage/qn-store/node_modules/qiniu/qiniu/rpc.js:75:9
    at done (/var/www/ghost/content/adapters/storage/qn-store/node_modules/urllib/lib/urllib.js:617:5)
    at /var/www/ghost/content/adapters/storage/qn-store/node_modules/urllib/lib/urllib.js:911:9
    at decodeContent (/var/www/ghost/content/adapters/storage/qn-store/node_modules/urllib/lib/urllib.js:699:14)
    at handleResponseCloseAndEnd (/var/www/ghost/content/adapters/storage/qn-store/node_modules/urllib/lib/urllib.js:876:7)
    at IncomingMessage.<anonymous> (/var/www/ghost/content/adapters/storage/qn-store/node_modules/urllib/lib/urllib.js:920:7)
    at IncomingMessage.emit (events.js:215:7)
    at IncomingMessage.EventEmitter.emit (domain.js:475:20)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

在上传图片的时候，会几率性的出现 token 过期的情况。重启 ghost 之后可以恢复，但是一段时间以后又会出现这个 token 过期的错误。

**Comment by JaxsonWang** [comment]
![image](https://user-images.githubusercontent.com/16836692/92495393-6e84cf80-f229-11ea-92a8-a10f3b55679f.png)

已遇到，有时间修复。

临时解决：`ghost restart` 可以解决。

**Comment by JaxsonWang** [comment]
Fix to https://github.com/JaxsonWang/Ghost-QiNiu-Store/commit/fa0500496349e3c7cd2117b4621ab88000d906b5
